FROM ghcr.io/rubyonracetracks/image-debian-<SUITE>-min-stage1

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/winner/docker-debian-install

COPY . .

RUN sudo chown -R winner:winner /home/winner/docker-debian-install && \
    cd /home/winner/docker-debian-install && bin/main
